name: CI

on:
  push:
    branches:
      - main
      - "feat/**"
      - "feature/**"
      - "fix/**"
      - "refactor/**"
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Install dependencies
        run: go mod download

      - name: Vet
        run: go vet ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.11.4

      - name: Build
        run: go build ./...

      - name: Start test database
        run: docker compose -f deployments/docker/compose.test.yaml up -d --wait db-test

      - name: Run tests
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: nanoninja/dojo

      - name: Stop test database
        if: always()
        run: docker compose -f deployments/docker/compose.test.yaml down
